### PR TITLE
Fix google sign-out

### LINKED ISSUE #240: Fix google sign-out
> logging out keeps the stored google account so it is impossible to switch between google accounts
<sub>[View in Slack](https://cs495-group-workspace.slack.com/archives/CSD5JKT0F/p1588613936002700)</sub>

### PR DESCRIPTION
**Pull request by mayank99**
Apparently you need to sign out google separately from firebase

closes #240

### CODE REVIEW

File: lib/common/auth.dart [hunk 1]
```diff
@@ -39,5 +39,8 @@ class Auth {
     }
   }
 
-  Future<void> signOut() => _firebaseAuth.signOut();
+  Future<void> signOut() async {
+    _firebaseAuth.signOut();
+    if (await _googleSignIn.isSignedIn()) _googleSignIn.signOut();
```
Comment (TortoiseWrath) [inline lib/common/auth.dart:44]: all I can think of while reading this is
